# Generated by Django 5.1.7 on 2025-03-25 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_content_alter_culturalelement_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('article_create', 'Created Article'), ('article_edit', 'Edited Article'), ('article_published', 'Published Article'), ('article_rejected', 'Rejected Article'), ('personality_create', 'Created Personality'), ('personality_edit', 'Edited Personality'), ('cultural_create', 'Created Cultural Element'), ('cultural_edit', 'Edited Cultural Element'), ('media_upload', 'Uploaded Media'), ('comment', 'Posted Comment')], max_length=30),
        ),
    ]
