# Generated by Django 5.2.4 on 2025-07-30 06:48

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_social_media_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('excerpt', models.TextField(blank=True, help_text='A short summary of the content')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('personality', 'Personality'), ('cultural', 'Cultural Element')], max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('featured', 'Featured')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('type_data', models.JSONField(blank=True, default=dict, help_text='Type-specific fields stored as JSON')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='content_items', to='app.category')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_content', to=settings.AUTH_USER_MODEL)),
                ('states', models.ManyToManyField(blank=True, related_name='content_items', to='app.state')),
                ('tags', models.ManyToManyField(blank=True, related_name='content_items', to='app.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'published'], name='app_content_content_d5eb5f_idx'), models.Index(fields=['published_at'], name='app_content_publish_2bf937_idx'), models.Index(fields=['review_status'], name='app_content_review__5e0b36_idx'), models.Index(fields=['slug'], name='app_content_slug_0d2e71_idx')],
            },
        ),
    ]
