# Generated by Django 5.2.4 on 2025-07-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_content_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingedit',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlerevision',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlerevision',
            name='user',
        ),
        migrations.RemoveField(
            model_name='culturalelement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='culturalelement',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='culturalelement',
            name='states',
        ),
        migrations.RemoveField(
            model_name='culturalelement',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='pendingedit',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='author',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='states',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleRevision',
        ),
        migrations.DeleteModel(
            name='CulturalElement',
        ),
        migrations.DeleteModel(
            name='PendingEdit',
        ),
        migrations.DeleteModel(
            name='Personality',
        ),
    ]
