# Generated by Django 5.2.4 on 2025-07-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_old_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='type_data',
        ),
    ]
