# Generated by Django 5.2.4 on 2025-07-31 06:45

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_type_data_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='content',
            name='featured_image',
            field=app.fields.CompressedImageField(blank=True, null=True, upload_to='content/'),
        ),
    ]
