# Generated by Django 5.2.4 on 2025-07-31 07:09

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_state_image_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='featured_image',
            field=app.fields.CompressedImageField(blank=True, null=True, target_size_kb=80, upload_to='content/'),
        ),
    ]
