# Generated by Django 5.2.4 on 2025-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_content_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='info_box_data',
            field=models.JSONField(blank=True, default=dict, help_text="Structured data for info box display (e.g., {'Name': 'Peter', 'Age': '25'})"),
        ),
    ]
