# Generated by Django 5.2.4 on 2025-07-31 09:10

import app.fields
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_content_info_box_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_comment', models.CharField(blank=True, help_text='Brief explanation of changes', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content_text', tinymce.models.HTMLField()),
                ('excerpt', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('featured_image', app.fields.CompressedImageField(blank=True, null=True, target_size_kb=80, upload_to='content/revisions/')),
                ('info_box_data', models.JSONField(blank=True, default=dict)),
                ('categories_data', models.JSONField(blank=True, default=list, help_text='List of category IDs')),
                ('tags_data', models.JSONField(blank=True, default=list, help_text='List of tag IDs')),
                ('states_data', models.JSONField(blank=True, default=list, help_text='List of state IDs')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='app.content')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_revisions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content', 'status'], name='app_content_content_9a3601_idx'), models.Index(fields=['status', 'created_at'], name='app_content_status_f72005_idx'), models.Index(fields=['editor'], name='app_content_editor__edacc8_idx')],
            },
        ),
    ]
