# Generated by Django 5.2.4 on 2025-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contentrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrevision',
            name='info_box_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
