# Generated by Django 5.2.4 on 2025-08-02 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_contentrevision_info_box_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of approved edits'),
        ),
        migrations.AddField(
            model_name='content',
            name='protected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who applied protection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='protection_expires',
            field=models.DateTimeField(blank=True, help_text='When protection expires (if temporary)', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='protection_level',
            field=models.CharField(choices=[('unprotected', 'Unprotected'), ('semi_protected', 'Semi-protected'), ('protected', 'Protected'), ('fully_protected', 'Fully Protected')], default='unprotected', help_text='Wikipedia-style protection level', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='protection_reason',
            field=models.TextField(blank=True, help_text='Reason for protection (vandalism, edit wars, etc.)'),
        ),
        migrations.AddField(
            model_name='content',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this content for changes', related_name='watched_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
