# Generated by Django 5.2.4 on 2025-07-31 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('editor', 'Editor'), ('admin', 'Administrator')], default='viewer', max_length=20)),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter handle without @', max_length=50)),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('facebook_profile', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('reputation_points', models.IntegerField(default=0)),
                ('contribution_count', models.IntegerField(default=0)),
                ('email_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
