# Generated by Django 5.2.4 on 2025-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved_edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of approved edits'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_approve_edits',
            field=models.BooleanField(default=False, help_text="Whether user's edits are auto-approved"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mention_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications when mentioned'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejected_edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of rejected edits'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='revert_count',
            field=models.PositiveIntegerField(default=0, help_text="Number of times user's edits were reverted"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trust_score',
            field=models.FloatField(default=0.0, help_text='Calculated trust score based on edit history'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watch_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications for watched articles'),
        ),
    ]
