# Generated by Django 5.2.4 on 2025-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_approved_edit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('autoconfirmed', 'Autoconfirmed'), ('extended_confirmed', 'Extended Confirmed'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('admin', 'Administrator')], default='viewer', max_length=20),
        ),
    ]
